-- Central which-key group definitions.
-- Individual keymaps still register via `desc` in vim.keymap.set / lazy `keys`.
return {
    { '<leader>', group = 'Leader' },
    { '<leader>?', desc = '[?] Show keymap help' },

    { '<leader><leader>', group = '[ ] Buffers' },
    { '<leader>/', desc = '[/] Search current buffer' },
    { '<leader>f', desc = '[F]ormat buffer' },
    { '<leader>q', desc = '[Q]uickfix diagnostics' },

    { '<leader>l', group = '[L]ine text', mode = { 'n', 'x' } },
    { '<leader>lp', desc = '[L]ine [P]refix', mode = { 'n', 'x' } },
    { '<leader>ls', desc = '[L]ine [S]uffix', mode = { 'n', 'x' } },

    { '<leader>s', group = '[S]earch' },
    { '<leader>sh', desc = '[S]earch [H]elp' },
    { '<leader>sk', desc = '[S]earch [K]eymaps' },
    { '<leader>sf', desc = '[S]earch [F]iles' },
    { '<leader>sg', desc = '[S]earch by [G]rep' },
    { '<leader>sw', desc = '[S]earch current [W]ord', mode = { 'n', 'x' } },
    { '<leader>s/', desc = '[S]earch open files' },
    { '<leader>ss', desc = '[S]earch Telescope pickers' },
    { '<leader>sd', desc = '[S]earch [D]iagnostics' },
    { '<leader>sr', desc = '[S]earch [R]esume' },
    { '<leader>s.', desc = '[S]earch recent files' },
    { '<leader>sn', desc = '[S]earch [N]eovim config' },
    { '<leader>g', group = '[G]it' },
    { '<leader>h', group = '[H]arpoon / Git hunk', mode = { 'n', 'v' } },
    { '<leader>o', group = '[O]pencode' },
    { '<leader>t', group = '[T]oggle' },
    { '<leader>tt', desc = '[T]oggle [T]erminal' },
    { '<leader>tm', desc = '[T]oggle [M]arkdown render' },
    { '<leader>td', desc = '[T]oggle [D]iagnostics display' },

    { '<leader>m', group = '[M]arkdown' },
    { '<leader>mp', desc = '[M]arkdown [P]review' },

    { '<leader>gd', desc = '[G]it [D]iffview open' },
    { '<leader>gD', desc = '[G]it [D]iffview close' },
    { '<leader>gh', desc = '[G]it [H]istory' },
    { '<leader>gH', desc = '[G]it history current file' },

    { '<leader>he', desc = '[H]arpoon list' },
    { '<leader>ha', desc = '[H]arpoon [A]dd file' },
    { '<leader>h1', desc = '[H]arpoon slot 1' },
    { '<leader>h2', desc = '[H]arpoon slot 2' },
    { '<leader>h3', desc = '[H]arpoon slot 3' },
    { '<leader>h4', desc = '[H]arpoon slot 4' },

    { '<leader>hs', desc = 'Git [s]tage hunk', mode = { 'n', 'v' } },
    { '<leader>hr', desc = 'Git [r]eset hunk', mode = { 'n', 'v' } },
    { '<leader>hS', desc = 'Git [S]tage buffer' },
    { '<leader>hu', desc = 'Git [u]ndo stage hunk' },
    { '<leader>hR', desc = 'Git [R]eset buffer' },
    { '<leader>hp', desc = 'Git [p]review hunk' },
    { '<leader>hb', desc = 'Git [b]lame line' },
    { '<leader>hd', desc = 'Git [d]iff against index' },
    { '<leader>hD', desc = 'Git [D]iff against last commit' },

    { '<leader>oa', desc = '[O]pencode [A]sk', mode = { 'n', 'x' } },
    { '<leader>ox', desc = '[O]pencode e[X]ecute', mode = { 'n', 'x' } },
    { '<leader>ot', desc = '[O]pencode [T]oggle', mode = { 'n', 't' } },

    { '<leader>tb', desc = '[T]oggle git [b]lame line' },
    { '<leader>tD', desc = '[T]oggle git inline [D]eleted' },

    { 'gr', group = 'LSP' },
    { 'grn', desc = 'LSP: [R]e[n]ame' },
    { 'gra', desc = 'LSP: code [A]ction', mode = { 'n', 'x' } },
    { 'grr', desc = 'LSP: [R]eferences' },
    { 'gri', desc = 'LSP: [I]mplementation' },
    { 'grd', desc = 'LSP: [D]efinition' },
    { 'grD', desc = 'LSP: [D]eclaration' },
    { 'gO', desc = 'LSP: document symb[O]ls' },
    { 'gW', desc = 'LSP: [W]orkspace symbols' },
    { 'grt', desc = 'LSP: [T]ype definition' },
    { '<leader>th', desc = '[T]oggle inlay [H]ints' },
    { 'gx', desc = 'Open link under cursor' },
    { ']c', desc = 'Next git change' },
    { '[c', desc = 'Previous git change' },
}
